### ISSUE TITLE
Improve form layout

### ISSUE THREAD

**Issue by tlylt** [kishore-a00/FoodIsGood-Orbital2022#17]
Consider giving some thoughts on how to better organize the form. At the moment it's too basic. The square buttons, title text etc need not fully fill the entire screen. Consider adding more margins/paddings, and explore other shapes, colors, and layout formats.

May also want to take inspiration from design websites like:
https://dribbble.com/shots/popular/mobile

![image](https://user-images.githubusercontent.com/41845017/177006026-2565bdd3-a8c5-488a-8ad8-24aecfeb222f.png)

**Comment by kishore-a00** [comment]
Updated the screens to (hopefully) look nicer than it is in the image above.
Added rounded corners to touchable opacity, and used a light blue background instead of this dark green colour.
Each button now has the ability to display an image (of the corresponding item) along with the name of the item below it.
Text has been bolder and made larger for ease of viewing.
